const duckBreeds: readonly string[] = [
  "Abacot Ranger",
  "Alabio",
  "Allier",
  "Ancona",
  "Appleyard",
  "Aylesbury",
  "Bac Kinh",
  "Bali",
  "Bashkir",
  "Bau",
  "Blekinge",
  "Bourbourg",
  "Cayuga",
  "Challandais",
  "Chara-Chemballi",
  "Dendermond",
  "Deshi Black",
  "Duclair",
  "Estaires",
  "Faroese",
  "German Pekin",
  "Germanata Veneta",
  "Gimbsheimer",
  "Golden Cascade",
  "Grimao Ermaos",
  "Haut-Volant",
  "Havanna",
  "Herve",
  "Huttegem",
  "Indian Runner",
  "Idegem",
  "Japanice Criollo",
  "Jending",
  "Kaiya",
  "Khaki Campbell",
  "Laplaigne",
  "Merchtem",
  "Naked Neck",
  "Orpington",
  "Overberg",
  "Pomeranian",
  "Rouen Clair",
  "Saxony",
  "Semois",
  "Shetland",
  "Silver Bantam",
  "Swedish Blue",
  "Tea Kapa",
  "Termonde",
  "Tsaiya",
  "Ukrainian Clay",
  "Venetian",
  "Vouille",
  "Welsh Harlequin",
  "Watervale",
  "White-breasted black"
] as const;

export function pickRandomDuckBreed(randomValue: number = Math.random()): string {
  const safeRandomValue = Number.isFinite(randomValue) ? randomValue : Math.random();
  const normalizedRandom = Math.min(Math.max(safeRandomValue, 0), 0.9999999999999999);
  const index = Math.floor(normalizedRandom * duckBreeds.length);
  return duckBreeds[index];
}
